### ISSUE TITLE
Timeout option in testNG making log messages unsent

### ISSUE THREAD

**Issue by rbhbokka** [reportportal/client-java-core#6]
_Dependencies:_ 
    agent-java-testng:2.6.0
    logger-java-log4j:2.6.0
    logger-java-logback:2.6.0
    org.testng:testng:6.9.8
    org.apache.logging.log4j:log4j-core:2.4

_Bug description:_
    User use testNG as a test runner. If test item have a timeout, log is not being sent to RP.

\<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
\<suite name="Menu" verbose="1" time-out="1">

Looks like this issue is related to a https://github.com/cbeust/testng/issues/914

TestNG creating separate threads for all test items if timeout is set. Then we have situation while runningNowItemId field in ReportPortalListenerContext.java is being set from test item thread, and read from main thread on a log message creation. As runningNowItemId is a ThreadLocal object we will get null value in main thread.

**Comment by avarabyeu** [comment]
cbeust/testng#914

**Comment by avarabyeu** [comment]
@rbhbokka could you please check an issue with new client version (3.0.0)?

**Comment by avarabyeu** [comment]
Since this component is not used anymore, closing the issue due to inactivity.
